#!/bin/bash

set -ux

if [ "$DIB_ROLE" == "controller" ] ; then
  HOSTNAME="controller00"
elif [ "$DIB_ROLE" == "compute" ] ; then
  HOSTNAME="compute000"
else
  echo "DIB_ROLE must be either 'controller' or 'compute'."
  exit 1
fi

echo $HOSTNAME > /etc/hostname
