#!/bin/bash

set -u

if [ "$DIB_ROLE" == "controller" ] ; then
  ip="192.168.25.4"
elif [ "$DIB_ROLE" == "compute" ] ; then
  ip="192.168.25.5"
else
  echo "DIB_ROLE must be either 'controller' or 'compute'."
  exit 1
fi

cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

auto eth2
iface eth2 inet dhcp

auto eth2.25
iface eth2.25 inet manual
vlan-raw-device eth2

auto br_infracloud
iface br_infracloud inet static
address $ip
netmask 255.255.255.0
gateway 192.168.25.1
bridge_ports eth2.25
bridge_hello 2
bridge_maxage 12
bridge_stp off
EOF
